version: '3.8'

services:
  predictor:
    image: ${PREDICTOR_IMAGE}
    container_name: dbbikes-predictor
    ports:
      - "5000:5000"
    restart: always
    mem_limit: 512m
    cpus: 0.5

  scraper:
    image: ${SCRAPER_IMAGE}
    container_name: dbbikes-scraper
    env_file:
      - ./scraper/.env.prod
    restart: on-failure
    mem_limit: 300m
    cpus: 0.3
