services:
  predictor:
    image: ${PREDICTOR_IMAGE}
    container_name: dbbikes-predictor
    ports:
      - "5000:5000"
    networks:
      - dbbikes-network
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: ${BACKEND_IMAGE}
    container_name: dbbikes-backend
    env_file:
      - ../backend/.env.prod
    ports:
      - "8080:8080"
    depends_on:
      - predictor
    networks:
      - dbbikes-network
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: dbbikes-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - predictor
    networks:
      - dbbikes-network
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  scraper:
    image: ${SCRAPER_IMAGE}
    container_name: dbbikes-scraper
    env_file:
      - ./scraper/.env.prod
    networks:
      - dbbikes-network
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dbbikes-network:
